theme: minima
title: ""
description: ""
show_excerpts: false
markdown: kramdown
baseurl: ""
url: "https://your-username.github.io/stellar-magnetism-workshop-2025"

# Disable header/footer duplication
minima:
  skin: classic
  date_format: "%b %-d, %Y"
  social_links: false
  show_title: false
  show_footer: false
