theme: minima
title: ""
description: ""
show_excerpts: false
markdown: kramdown
url: "https://rahulkashyap-phy.github.io"
baseurl: "/MagnetizedStars-Remnants_workshopDec2025"


# Disable header/footer duplication
minima:
  skin: classic
  date_format: "%b %-d, %Y"
  social_links: false
  show_title: false
  show_footer: false
