theme: minima
title: Stellar Magnetism Workshop 2025
description: Workshop on Magnetism in Low-Mass Stars and Compact Remnants
baseurl: ""
url: "https://your-username.github.io/stellar-magnetism-workshop-2025"
markdown: kramdown
